#!/bin/bash

make

./assembler input/comments.s out/comments.int out/comments.out 
diff out/comments.out out/ref/comments_ref.out

./assembler input/combined.s out/combined.int out/combined.out 
diff out/combined.out out/ref/combined_ref.out

./assembler input/imm.s out/imm.int out/imm.out 
diff out/imm.out out/ref/imm_ref.out

./assembler input/jumps.s out/jumps.int out/jumps.out 
diff out/jumps.out out/ref/jumps_ref.out

./assembler input/labels.s out/labels.int out/labels.out 
diff out/labels.out out/ref/labels_ref.out

./assembler input/pseudo.s out/pseudo.int out/pseudo.out 
diff out/pseudo.out out/ref/pseudo_ref.out

./assembler input/rtypes.s out/rtypes.int out/rtypes.out 
diff out/rtypes.out out/ref/rtypes_ref.out

./assembler input/simple.s out/simple.int out/simple.out 
diff out/simple.out out/ref/simple_ref.out

./assembler -p1 input/p1_errors.s out/p1_errors.int -log log/p1_errors.txt
diff log/p1_errors.txt log/ref/p1_errors_ref.txt

./assembler input/p2_errors.s out/p2_errors.int out/p2_errors.out -log log/p2_errors.txt
diff log/p2_errors.txt log/ref/p2_errors_ref.txt